### ISSUE TITLE
1.16 Unsupported 

### ISSUE THREAD

**Issue by Fonzie015** [Gyzerc/LegendaryGuild#4]
[02Feb2024 13:44:21.114] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins\LegendaryGuild-5.0.8-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbersMixin.java:304) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:141) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServerMixin.java:381) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at net.minecraft.server.dedicated.DedicatedServer.handler$bbf000$arclight$loadPlugins(DedicatedServerMixin.java:637) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:160) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by Gyzerc** [comment]
Open the plugin using a compressed file method, open plugin.yml, and modify the API version to 1.16
